services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:80"
    networks:
      - mappo
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8080"
    networks:
      - mappo 

  flask_server:
    build:
      context: ./ml_pipeline
    ports:
      - "5001:5001"
    networks:
      - mappo

networks:
  mappo:
    driver: bridge