services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:80"
    networks:
      - mappo

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8080"
    environment:
      - DefaultConnection=${DefaultConnection}
    networks:
      - mappo 

networks:
  mappo:
    driver: bridge
