services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:80"
    networks:
      - mappo
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8080"
    environment:
      - DefaultConnection=${DefaultConnection}
    networks:
      - mappo 

  flask_server:
    build:
      context: ./ml_pipeline
    ports:
      - "5001:5001"
    networks:
      - mappo
    volumes:
      - ./ml_pipeline:/app/ml_pipeline

networks:
  mappo:
    driver: bridge
    