services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - pinbox

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8080"
    environment:
      - DefaultConnection=${DefaultConnection}
    networks:
      - pinbox 

networks:
  pinbox:
    driver: bridge
    