name: Python Unit Testing

on:
  pull_request:
    branches:
      - dev
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Check Python version and pip version
      run: |
        python --version
        pip --version

    - name: Upgrade pip
      run: |
        python -m pip install --upgrade pip

    - name: Install dependencies
      run: |
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pytest  # Install pytest directly

    - name: Test with pytest
      run: |
        pytest
